# Default values for steward-crds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Overrides the name of the chart for resource naming purposes.
nameOverride: ""
# -- Overrides the full name of the resources created by the chart.
fullnameOverride: ""

# -- The namespace where Steward has been installed: required to inject the Certificate Authority for cert-manager.
stewardNamespace: steward-system
# -- The Steward webhook Service name.
stewardService: steward-webhook-service
# -- The cert-manager Certificate resource name, holding the Certificate Authority for webhooks.
stewardCertificateName: steward-serving-cert
