apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    {{- $data := . | mustMergeOverwrite (dict "component" "issuer") -}}
    {{- include "steward.labels" $data | nindent 4 }}
  name: steward-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}