- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: '{{ include "steward.webhookServiceName" . }}'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-steward-butlerlabs-dev-v1alpha1-datastore
  failurePolicy: Fail
  name: vdatastore.kb.io
  rules:
    - apiGroups:
        - steward.butlerlabs.dev
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
        - DELETE
      resources:
        - datastores
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: '{{ include "steward.webhookServiceName" . }}'
      namespace: '{{ .Release.Namespace }}'
      path: /validate--v1-secret
  failurePolicy: Ignore
  name: vdatastoresecrets.kb.io
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      operations:
        - DELETE
      resources:
        - secrets
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: '{{ include "steward.webhookServiceName" . }}'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-steward-butlerlabs-dev-v1alpha1-tenantcontrolplane
  failurePolicy: Fail
  name: vtenantcontrolplane.kb.io
  rules:
    - apiGroups:
        - steward.butlerlabs.dev
      apiVersions:
        - v1alpha1
      operations:
        - CREATE
        - UPDATE
      resources:
        - tenantcontrolplanes
  sideEffects: None
