apiVersion: v2
appVersion: v0.2.2
description: Steward is the Hosted Control Plane Manager for Kubernetes.
home: https://github.com/butlerdotdev/steward
icon: https://github.com/butlerdotdev/steward/raw/main/assets/logo.png
kubeVersion: ">=1.21.0-0"
maintainers:
  - email: andrew@butlerlabs.dev
    name: Andrew Bagan
    url: https://butlerlabs.dev
name: steward
sources:
  - https://github.com/butlerdotdev/steward
type: application
version: 0.2.2
dependencies:
  - name: steward-etcd
    version: "0.14.0"
    repository: "oci://ghcr.io/butlerdotdev/charts"
    condition: steward-etcd.deploy
annotations:
  artifacthub.io/crds: |
    - kind: TenantControlPlane
      version: v1alpha1
      name: tenantcontrolplanes.steward.butlerlabs.dev
      displayName: TenantControlPlane
      description: TenantControlPlane defines the desired state for a Control Plane backed by Steward.
    - kind: DataStore
      version: v1alpha1
      name: datastores.steward.butlerlabs.dev
      displayName: DataStore
      description: DataStore holds connection details for backend storage (etcd, MySQL, PostgreSQL, NATS).
    - kind: KubeconfigGenerator
      version: v1alpha1
      name: kubeconfiggenerators.steward.butlerlabs.dev
      displayName: KubeconfigGenerator
      description: KubeconfigGenerator generates kubeconfig files for TenantControlPlane access.
  artifacthub.io/links: |
    - name: Butler Labs
      url: https://butlerlabs.dev
    - name: Documentation
      url: https://github.com/butlerdotdev/steward/tree/main/docs
  artifacthub.io/license: Apache-2.0
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: "full lifecycle"
