apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "steward-crds.certManagerAnnotation" . }}
  labels:
    {{- include "steward-crds.labels" . | nindent 4 }}
  name: datastores.steward.butlerlabs.dev
spec:
  {{ tpl (.Files.Get "hack/steward.butlerlabs.dev_datastores_spec.yaml") . | nindent 2}}
